# Generated by Django 5.0.2 on 2024-02-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0002_alter_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=256),
        ),
    ]
